### ISSUE TITLE
fma32

### ISSUE THREAD

**Issue by Vutshi** [nschloe/pyfma#13]
Hi,

Thank you for the great tool. I am curious whether it is difficult to add support of FMA operation for `float` numbers additionally to the current `double` implementation. It would be really helpful for testing and debugging various numerical algorithms in plenty of software using `float` due to speed reasons.

Cheers

**Comment by nschloe** [comment]
The new pyfma version also supports np.float32 and np.float128 arrays (float, long double in C).
