### ISSUE TITLE
Build failure on macOS Catalina

### ISSUE THREAD

**Issue by SerpentChris** [nschloe/pyfma#3]
I have Python 3.8 installed on my Mac via MacPorts. In a new venv, doing `pip install pyfma` results in a failure, and looking at the errors it is caused by failing to include the flag `-std=c++11`. Installing requires `CFLAGS='-std=c++11' pip install pyfma`.  My exact compiler version is `Apple clang version 12.0.0 (clang-1200.0.32.2)`, which is the compiler that comes with Xcode 12.

**Comment by SerpentChris** [comment]
Perhaps adding a check for macOS and then adding an extra compile flag like this in the setup.py would work:

```python
import sys

if sys.platform == 'darwin':
    extra_args = ['-std=c++11']
else:
    extra_args=[]

ext_modules = [
    Extension(
        "_pyfma",
        ["src/pybind11.cpp"],
        language="c++",
        include_dirs=[
            # Path to pybind11 headers
            get_pybind_include(),
            get_pybind_include(user=True),
        ],
        extra_compile_args=extra_args, # Add this keyword argument
    )
]
```

**Comment by nschloe** [comment]
Clangs default has been c++14 for many years now. Something wrong with your installation?

**Comment by nschloe** [comment]
Just updated pybind11, should be worth trying again.
